// Generated by CoffeeScript 1.12.7
(function() {
  var $;

  $ = domUtil;

  $(document).on('DOMContentLoaded', function(evt) {
    var changeMiddleInfo, galleryImageInterval, mediaQuery, showBGVideo, showBGVideoBaseOnMedieQuery, text_info_setting;
    mediaQuery = window.matchMedia("(all)");
    galleryImageInterval = void 0;
    text_info_setting = {
      0: {
        title: 'Blender Cycles 室内interior高质量作品',
        link: '/2018/05/29/blender-cycles-interior/',
        detail: '点击查看个人作品，<br/>照片级 3D 作品，基于现实设计，真实再现'
      },
      1: {
        title: 'Unreal Engine4 虚幻四作品 「林中小径」',
        link: '/2017/08/22/UE4-work-forest-path-with-panorama/',
        detail: '点击查看个人作品，<br/>使用UE4构建光影斑驳的森林场景 <br/>包含全景画方式浏览，360° & 180°观看四周'
      },
      2: {
        title: '神经网络算法转变 图画的艺术风格',
        link: '/2017/06/27/image-style-transfer-using-neural-style',
        detail: '点击查看一系列作品，纯粹由卷积神经网络算法生成的作品'
      }
    };
    changeMiddleInfo = (function(key_indices_to_infos) {
      var info, info_dom, text_info, text_info_dom;
      info = $(".gallery-middle-info-wrap .info-wrap .info");
      text_info = $(".gallery-middle-info-wrap .text-info");
      info_dom = info.get();
      text_info_dom = text_info.get();
      return function(key) {
        var item, replace_info, replace_link, replace_text_info;
        item = key_indices_to_infos[key];
        if (item) {
          replace_info = item["title"];
          replace_link = item["link"];
          replace_text_info = item["detail"];
          if (replace_info) {
            info_dom.innerText = replace_info;
          }
          if (replace_link) {
            info.setAttributes({
              href: replace_link
            });
          }
          if (replace_text_info) {
            return text_info_dom.innerHTML = replace_text_info;
          }
        }
      };
    })(text_info_setting);
    showBGVideo = (function() {
      var is_show, time2key;
      is_show = false;
      time2key = {
        0: 1,
        12: 1,
        24: 2
      };
      return function() {
        var gallery, images, ref, v, videoSource;
        if (!is_show) {
          v = document.createElement("video");
          videoSource = 'videos/BookRoom.mkv';
          $(v).setAttributes({
            loop: 'loop',
            muted: 'muted',
            preload: 'auto',
            autoplay: 'autoplay',
            src: videoSource
          }).on('timeupdate', (function(_this) {
            return function(evt) {
              var key, now;
              now = evt.target.currentTime.toFixed(0);
              key = time2key[now];
              if (key) {
                return changeMiddleInfo(key);
              }
            };
          })(this));
          gallery = $(".gallery");
          gallery.get().appendChild(v);
          images = (ref = $("img", gallery)) != null ? ref.css({
            display: 'none'
          }) : void 0;
          if (galleryImageInterval) {
            clearInterval(galleryImageInterval);
          }
          return is_show = true;
        }
      };
    })();
    showBGVideoBaseOnMedieQuery = function(mediaQuery) {
      if (mediaQuery.matches) {
        return showBGVideo();
      } else {

      }
    };
    (function(mediaQuery) {
      var clientJumpTo, gallery, galleryJumpTo, i, imageGalleryControl, image_hide_sytle, image_show_sytle, images, img, len;
      if (!mediaQuery.matches) {
        image_show_sytle = {
          opacity: 1
        };
        image_hide_sytle = {
          opacity: 0
        };
        gallery = $(".gallery");
        images = $("img.gallery-image", gallery);
        if (!images.length) {
          images = [images];
        }
        images.css(image_hide_sytle);
        images[0].css(image_show_sytle);
        for (i = 0, len = images.length; i < len; i++) {
          img = images[i];
          if (!img.get().getAttribute("src")) {
            img.setAttributes({
              src: img.get().getAttribute("data-src")
            });
          }
        }
        galleryJumpTo = function(idx) {
          var target_elem_id;
          images = $("img.gallery-image", gallery);
          if (idx >= images.length || idx < 0) {
            idx = 0;
          }
          target_elem_id = "gallery-image-" + (idx + 1);
          $('#gallery-image-' + (idx + 1), gallery).css(image_show_sytle);
          images.forEach(function(img) {
            if (target_elem_id === img.getAttribute("id")) {
              return img.css(image_show_sytle);
            } else {
              return img.css(image_hide_sytle);
            }
          });
          return changeMiddleInfo(idx);
        };
        imageGalleryControl = (function() {
          var galleryImageLoop, next_id, resetGallery, stopGallery;
          next_id = 0;
          galleryImageLoop = function() {
            if (next_id >= images.length) {
              next_id = 0;
            }
            galleryJumpTo(next_id);
            return next_id += 1;
          };
          galleryImageLoop();
          galleryImageInterval = setInterval(galleryImageLoop, 7500);
          stopGallery = function() {
            if (galleryImageInterval) {
              return clearInterval(galleryImageInterval);
            }
          };
          resetGallery = function(now_idx) {
            if (galleryImageInterval) {
              stopGallery();
            }
            if (now_idx) {
              next_id = now_idx + 1;
            }
            return galleryImageInterval = setInterval(galleryImageLoop, 7500);
          };
          return {
            stopGallery: stopGallery,
            resetGallery: resetGallery
          };
        })();
        clientJumpTo = function(idx) {
          galleryJumpTo(idx);
          return imageGalleryControl.resetGallery(idx);
        };
        $(".gallery-jump-point", gallery).forEach(function(jumpPoint) {
          var idx;
          idx = parseInt(jumpPoint.getAttribute('data-idx'), 10);
          return jumpPoint.on("click", function(event) {
            return clientJumpTo(idx);
          });
        });
      }
    })(mediaQuery);
  });

}).call(this);
